# Generated by Django 2.2 on 2019-04-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
